odev5/Controllers/AnasayfaController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace odev5.Controllers
{
    public class AnasayfaController : Controller
    {
        // GET: Home
        public ActionResult Anasayfa()
        {

            String dil = Request.QueryString["Language"];

            if (@dil != null)
            {

                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(@dil);
                Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture(@dil);

                HttpCookie cookie = new HttpCookie("Language");
                cookie.Value = @dil;
                Response.Cookies.Add(cookie);

            }

            return View();
        }
        // GET: Home
        public ActionResult Anneme()
        {
            return View();
        }
        // GET: Home
        public ActionResult Cocuguma()
        {
            return View();
        }
        // GET: Home
        public ActionResult Aktiviteler()
        {
            return View();
        }
        public ActionResult Psikologlar()
        {
            return View();
        }
    }
}

odev5/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@odev5.Resources.Language.uygulama_adi</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/admin.bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/Yonetim/Anasayfa">@odev5.Resources.Language.uygulama_adi</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/Yonetim/Anasayfa">Anasayfa</a></li>
                    <li><a href="/Yonetim/Kullanicilar">Kullanıcılar</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/Anasayfa/Anasayfa">Siteyi Görüntüle</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @odev5.Resources.Language.uygulama_adi</p>
        </footer>
    </div>
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
        <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

odev5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@odev5.Resources.Language.uygulama_adi</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(@odev5.Resources.Language.uygulama_adi, "Anasayfa", "Anasayfa", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/Anasayfa/Anneme">@odev5.Resources.Language.link1</a></li>
                    <li><a href="/Anasayfa/Cocuguma">@odev5.Resources.Language.link2</a></li>
                    <li><a href="/Anasayfa/Aktiviteler">@odev5.Resources.Language.link3</a></li>
                    <li><a href="/Anasayfa/Psikologlar">@odev5.Resources.Language.link4</a></li>
                    <li><a href="/Kullanici/Yeni">@odev5.Resources.Language.link5</a></li>
                    <li><a href="/Kullanici/Giris">@odev5.Resources.Language.link6</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/Anasayfa/Anasayfa?Language=tr">Türkçe</a></li>
                    <li><a href="/Anasayfa/Anasayfa?Language=en">English</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @odev5.Resources.Language.uygulama_adi</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>